import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Account.module.css";

import React, { useState, useContext } from "react";

import { AppContext } from "@/context/AppContext";

import Background from '@/public/Background.gif'
import Navbar from "@/components/NavBar";
import QuestDoneBox from "@/components/QuestDoneBox";

import Account from '@/public/icons/Account.svg'
import BtnWhite from "@/components/BtnWhite";
import UserLogout from "@/firebase/UserLogout";

export default function Home() {
  const { quests, userName } = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.page} style={{
        backgroundImage: `url(${Background.src})`,
        backgroundRepeat: 'repeat',
      }}>
        <div className={styles.classCont}>
          <div className={styles.accountHead}>
            <div className={styles.accountHeadLeft}>
              <Image src={Account} width={60} height={60}/>
              <p>{userName}</p>
            </div>
            <UserLogout />
          </div>
          <h1>Quests Completed</h1>
          {
            quests && quests.map((q, index) => {
              if (q.done === true) return <QuestDoneBox key={index} quest={q} />
            })
          }
        </div>
        <Navbar />
      </main>
    </>
  );
}