import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import React, { useState, useContext } from "react";

import QuestBox from "@/components/QuestBox";

import { AppContext } from "@/context/AppContext";

import Background from '@/public/Background.gif'
import QuestForm from "@/components/QuestForm";
import Navbar from "@/components/NavBar";

import UserRegister from "@/firebase/UserRegister";
import UserLogin from "@/firebase/UserLogin";

export default function Home() {
  const { quests, formActive, display } = useContext(AppContext);

  return (
    <>
      <Head>
        <title>QuestLyne</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.page} style={{
        backgroundImage: `url(${Background.src})`,
        backgroundRepeat: 'repeat',
      }}>
        {
          display === "home" ? <>
            {
              quests.length === 0 || quests.every((q) => q.done == true) ? <div className={styles.noQuestCont}>
                Add a QuestLyne You Loser...
              </div> : <div className={styles.questCont}>{
                quests && quests.map((q, index) => {
                  if (q.done == false) return <QuestBox key={index} quest={q} />
                })
              }</div>
            }
            {
              formActive ? <QuestForm /> : <></>
            }

            <Navbar />
          </> : display === "register" ? <UserRegister /> : <UserLogin />
        }

      </main>
    </>
  );
}